### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 93ams** [martalima11/CPD#5]
- [ ] Decidir quando retornar tasks dos slaves para o master para load balancing.
- [x] Ter SWAG!
- [x] Implementar pruning no master (em principio aquando da recepção de tasks)
- [ ] Adicionar OpenMP
- [x] Criar funções de conversão node2task
- [x] Criar função de eliminação de tasks da task queue
